#pragma once


#define MY_DEVICE 0x8000
#define IOCTL_MY_DRIVER_READ CTL_CODE(MY_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MY_DRIVER_WRITE CTL_CODE(MY_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MY_DRIVER_FORWARD CTL_CODE(MY_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
