#pragma once


#define MY_DEVICE 0x8000
#define IOCTL_DRIVER_INIT_TPOOL CTL_CODE(MY_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_PROCESS_TPOOL CTL_CODE(MY_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_UNINIT_TPOOL CTL_CODE(MY_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
