#pragma once

#include "driver_filtering.h"


#define IOCTL_PROCESS_PROTECT_BY_PID CTL_CODE(0x8000, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_UNPROTECT_BY_PID CTL_CODE(0x8000, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_PROTECT_CLEAR CTL_CODE(0x8000, 0x806, METHOD_NEITHER, FILE_ANY_ACCESS)
